services:
  postgres:
    image: postgres:16
    container_name: incident-postgres
    environment:
      POSTGRES_USER: incident_user
      POSTGRES_PASSWORD: incident_pass
      POSTGRES_DB: incident_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: incident-backend
    environment:
      DATABASE_URL: postgresql://incident_user:incident_pass@postgres:5432/incident_db
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: incident-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
